### ISSUE TITLE
Search and play albums

### ISSUE THREAD

**Issue by deadcombo** [okonek/tidal-cli-client#12]
I see that the api has a search type for albums, is it possible to use this to browse an artist's catalog and play an entire album? This would be a great improvement over playing up to two songs at a time.

Anyway, thank you very much for creating `tidal-cli`! As a Firefox user, it's wonderful to have  Hi-Fi playback in linux.

**Comment by okonek** [comment]
Currently I'm working on playlists, but the next thing will be albums.

**Comment by deadcombo** [comment]
Well, thank you. It's good to know you'll keep developing!

**Comment by okonek** [comment]
I have added album search option recently and soon you'll be able to see albums in artist panel too.

**Comment by deadcombo** [comment]
That's great to hear! I'll really enjoy that!
Thank you for continuing to work on this, it's really great.

**Comment by okonek** [comment]
In the latest update 1.4.0 I have added listing albums in artist panel, so closing. :)
