### ISSUE TITLE
Main app not responding.

### ISSUE THREAD

**Issue by da022414** [okonek/tidal-cli-client#13]
After submitting username and password, main app loads, but won't respond.

**Comment by da022414** [comment]
After a few more attempts, I got it to work.

**Comment by okonek** [comment]
Could you give me your system and how have you installed this app. Also have you got MPV and W3M?

**Comment by da022414** [comment]
I’m running on Solus, installed via ‘sudo npm -g i tidal-cli-client@latest’ and MPV and W3M are both up to date.

**Comment by okonek** [comment]
How did you resolved the issue?
