### ISSUE TITLE
Client freezes on start-up

### ISSUE THREAD

**Issue by pafluxa** [okonek/tidal-cli-client#22]
Greeting, 

Upon executing

`npm run app`

The terminal emulator just stays blank. No error messages are shown. 

This is on Ubuntu 16.04. MPV and W3M are installed. Please let me know if I should provide more information about my setup.

Best,

 - Pedro.

**Comment by okonek** [comment]
You downloaded it using git clone or npm?

**Comment by pafluxa** [comment]
Hi, 

I tried both, neither seems to work.

 - Pedro

**Comment by okonek** [comment]
Have you logged in?

**Comment by pafluxa** [comment]
I am 99% sure I am.

 - Pedro.

**Comment by okonek** [comment]
So you passed your data, logged in and then it crashed?

**Comment by pafluxa** [comment]
It doesn't actually _crash_, it just gives me a blank terminal.

**Comment by okonek** [comment]
Are you sure, you have written your data correctly? You can see it in a file: /home/_username_/.tidalConfig.js

**Comment by pafluxa** [comment]
Yes I can.

**Comment by pafluxa** [comment]
I discovered the issue.

I had to uninstall w3m from the system and install w3m-img. 

 - Pedro.

**Comment by okonek** [comment]
So now you have only w3m-img installed no w3m, yes? If so, could you try installing w3m now and see if it works with it? Thank you!

**Comment by okonek** [comment]
I'm closing
