### ISSUE TITLE
App stops working when pressing Ctrl+P 

### ISSUE THREAD

**Issue by CodaTheOtaku** [okonek/tidal-cli-client#24]
Hello, so when I updated the app which has things such playlists and albums, I go to press Control-P to load my playlists and I get this:

`(node:13454) UnhandledPromiseRejectionWarning: undefined
(node:13454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13454) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any idea what the issue may be?

**Comment by okonek** [comment]
I'm working on it

**Comment by okonek** [comment]
Now there is no error.
