### ISSUE TITLE
newest version wont run in fedora container due to incorrect detection of dependency

### ISSUE THREAD

**Issue by twhiston** [okonek/tidal-cli-client#25]
So i install all the dependencies that the app requires in my dockerfile, and then get latest with npm but unfortunately now that you introduced dependency checking it fails to start due to mising W3M-IMG, however it is actually installed

Dockerfile
```
FROM fedora

RUN dnf localinstall -y --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN dnf install -y libstdc++
RUN dnf install -y git nodejs mpv w3m w3m-img

RUN npm -g i tidal-cli-client@latest

CMD tidal-cli
```

Docker build output shows it got installed
```
Step 5/7 : RUN dnf install -y git nodejs mpv w3m w3m-img
 ---> Running in e5c5fb99f281
Last metadata expiration check: 0:00:07 ago on Sun Apr  8 22:04:43 2018.
Dependencies resolved.
================================================================================
 Package                  Arch   Version                   Repository      Size
================================================================================
Installing:
 git                      x86_64 2.14.3-3.fc27             updates        1.1 M
 mpv                      x86_64 0.27.2-1.fc27             rpmfusion-free-updates
                                                                          962 k
 nodejs                   x86_64 2:8.11.1-1nodesource      nodesource      17 M
 w3m                      x86_64 0.5.3-36.git20180125.fc27 updates        1.0 M
 w3m-img                  x86_64 0.5.3-36.git20180125.fc27 updates         39 k

...
Installed:
  git.x86_64 2.14.3-3.fc27                                                      
  mpv.x86_64 0.27.2-1.fc27                                                      
  nodejs.x86_64 2:8.11.1-1nodesource                                            
  w3m.x86_64 0.5.3-36.git20180125.fc27                                          
  w3m-img.x86_64 0.5.3-36.git20180125.fc27     

...


Step 6/7 : RUN npm -g i tidal-cli-client@latest
 ---> Running in c78e08dd3d30
/usr/bin/tidal-cli -> /usr/lib/node_modules/tidal-cli-client/app/index.js
+ tidal-cli-client@1.4.4
```

Now trying to run it fails
```
docker run -it registry.twhiston.cloud/tomwhiston/tidal-cli     
You haven't got W3M-IMG installed
```

**Comment by leynebe** [comment]
Same issue without a container on Fedora 27.

> sudo yum install w3m-img
> Package w3m-img-0.5.3-36.git20180125.fc27.x86_64 is already installed, skipping.

> tidal-cli
> You haven't got W3M-IMG installed

**Comment by okonek** [comment]
Thank you, I'll try to solve it.

**Comment by okonek** [comment]
I have a question. Can you tell me, where is your w3m-img binary located?

**Comment by twhiston** [comment]
full path incuding binary name is `/usr/libexec/w3m/w3mimgdisplay`

**Comment by okonek** [comment]
Ok, thank you.

**Comment by okonek** [comment]
From the latest update you can manually set your w3m-img path in the config file, but your should be now supported out of the box. Let me know if it works.

**Comment by twhiston** [comment]
that is starting up now, thanks!
I think due to the container I have another issue now where nothing happens after i enter something to search for, what is the best way to see logging output from the program, so that I can find what is actually going on?

**Comment by okonek** [comment]
You type: "search" and then "track name", yes?

**Comment by twhiston** [comment]
I got it working so i think you can close this now. I
s it possible to write errors to logs in the app? I have some other issues in the container i'm using related to getting sound output but it's really hard to fix when I don't know how to see error output. I have other containers working with sound, so I think if i could see what was actually going wrong i could fix it.

**Comment by okonek** [comment]
I'll do my best to implement it.
