### ISSUE TITLE
Still getting syntax error

### ISSUE THREAD

**Issue by HowBoutSomeSnus** [okonek/tidal-cli-client#26]
/usr/lib/node_modules/tidal-cli-client/app/index.js:7
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

**Comment by okonek** [comment]
What version of node have you got?

**Comment by HowBoutSomeSnus** [comment]
How do I check that?

**Comment by okonek** [comment]
You type node -v in the terminal

**Comment by HowBoutSomeSnus** [comment]
v6.14.1

**Comment by okonek** [comment]
That means you should update Node.

**Comment by HowBoutSomeSnus** [comment]
And how would I go about that?

**Comment by okonek** [comment]
I don't know how to update node in Ubuntu. I think you should google it.

**Comment by okonek** [comment]
I plan adding volume control inside the app. About terminal, I would suggest you using urxvt. It's a very cutomizable and lightweight terminal. But speaking of your terminal. Could you please send a screenshot of this 'messed' stuff? 
Thanks.

**Comment by HowBoutSomeSnus** [comment]
Nice about the volume control being added. I tried urxvt, and it worked just fine, but how do I customize it? Config file? Anyways here's the screenshot: [https://imgur.com/a/NVxT9](https://imgur.com/a/NVxT9)
It seems to be half-transparent or something, as I can see some of my desktop poking through.
Thank you for your help and the awesome app.

**Comment by okonek** [comment]
The problem from screenshot is actually a w3m-img fault, but it's the only way to display images in terminal. You can customize urxvt with .Xresources file in your home directory. Here are some great configs. You'll find something for you. https://github.com/AntSunrise/URxvt-themes You can also edit them to fit your needs.

**Comment by HowBoutSomeSnus** [comment]
Ah, I see. Thank you for the tips.
