### ISSUE TITLE
npm run app fails

### ISSUE THREAD

**Issue by pafluxa** [okonek/tidal-cli-client#30]
Greetings,

When trying to run the app, I get this error.

> tidal-cli-client@1.5.1 app /home/pafluxa/software/tidal-cli-client
> node app/index.js

/home/pafluxa/software/tidal-cli-client/app/index.js:25
(async () => {
       ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Would you kindly take a look at this when you get the chance? I promise I'll make a donation if resolved :-)

Thanks,

 - Pedro.

**Comment by HowBoutSomeSnus** [comment]
I got the same issue, you need to update node

**Comment by pafluxa** [comment]
Hi,

I ran the instructions I found here

https://stackoverflow.com/questions/41195952/updating-nodejs-on-ubuntu-16-04

It seems to be working now.

Thanks!

 - Pedro.

**Comment by pafluxa** [comment]
Hi there again,

Answer to myself: I upgraded mpv to the latest version following these instructions

http://ubuntuhandbook.org/index.php/2016/07/install-mpv-media-player-ubuntu-16-04/

It now works! Thanks for the support :dagger: 

 - Pedro.

**Comment by HowBoutSomeSnus** [comment]
No worries! :)

**Comment by okonek** [comment]
@HowBoutSomeSnus Thank you very much for helping @pafluxa resolve his issue. You are awesome.
