### ISSUE TITLE
No playlist

### ISSUE THREAD

**Issue by picarda** [okonek/tidal-cli-client#35]
Hello,
I have nothing on my playlist.
Also can we browse albums?

Thank you

**Comment by deadcombo** [comment]
You need to create your playlists on the website or on the apps. Then they will appear after you press ctrl+P.

You can browse albums by typing ":", followed by "search", then "album" and finally the name of the album you're looking for.

I strongly recommend that you read the README page thoroughly before creating any more issues.

On June 7, 2018 10:08:02 PM GMT+01:00, Alain Picard <notifications@github.com> wrote:
>Hello,
>I have nothing on my playlist.
>Also can we browse albums?
>
>Thank you
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/okonek/tidal-cli-client/issues/35

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by picarda** [comment]
Thank you for the informations.
I didn't saw the quality streamed on the README.

Thanks

**Comment by okonek** [comment]
@deadcombo Thank you for your help.
