### ISSUE TITLE
Privacy: Sentry (Raven) Integration

### ISSUE THREAD

**Issue by sbrandtb** [okonek/tidal-cli-client#39]
I just checked out tilda-cli-client and ran into an exception while searching which, because it printed something like `raven@x.y.z alert: unhandled exception occured`, made me aware that you're using a Sentry integration here. Not checked further, but knowing how Sentry works, I'm now afraid to leak my password to your service.

That may be unwarranted, but still leaves a very bad feeling. It should be more like:

* crash happens
* window: "do you want to send crash report? here's what would be sent: {json}"
* i can choose yes/no/never/always

**Comment by okonek** [comment]
The code is open-source, so you can see how much data am i giving to sentry. I don't send any passwords or even your e-mails. Just the package version.

**Comment by okonek** [comment]
But I might add sending error logs as an optional feature.
