### ISSUE TITLE
no audio when playing music tidal-cli

### ISSUE THREAD

**Issue by mmonacelli1** [okonek/tidal-cli-client#44]
after installing all dependecies and tidal-cli, when playing music no audio.

**Comment by mmonacelli1** [comment]
I followed the previous post about reinstalling mpv and tidal.  did not work...  Any ideas?

**Comment by mmonacelli1** [comment]
Where the heck is this guy?  Its been 4 days since I posted and no comments at all??

**Comment by okonek** [comment]
Sorry, but I also sometimes have a free time. About the issue: what is your os? Are you sure, you have mpv? If yes, try playing some mp3 directly with mpv and check if it works.

**Comment by mmonacelli1** [comment]
Yes have up to date mpv.  I can play chopin wav directly in terminal.  But tidal says “playing “. But no sound.  Chked system volume settings.  Worked on open suse but centos(red hat) not working.  

When I played chopin test in terminal was that mpv?

Michael

YOU MATTER!
Sent from my iPhone

On Sep 14, 2018, at 06:27, Jan Okoński <notifications@github.com> wrote:

Sorry, but I also sometimes have a free time. About the issue: what is your os? Are you sure, you have mpv? If yes, try playing some mp3 directly with mpv and check if it works.

**Comment by mmonacelli1** [comment]
I might have did “play...  ill try it again and get back to you.

**Comment by okonek** [comment]
Sure

**Comment by okonek** [comment]
And?

**Comment by mmonacelli1** [comment]
Oh i deleted linux bc boot sequence got messed up.  Thks for your help.

YOU MATTER!
Sent from my iPhone

On Sep 21, 2018, at 13:06, Jan Okoński <notifications@github.com> wrote:

And?

**Comment by mmonacelli1** [comment]
Yeah 

YOU MATTER!
Sent from my iPhone

On Sep 22, 2018, at 10:22, Jan Okoński <notifications@github.com> wrote:

So, can I close?
