### ISSUE TITLE
Freezes at donation

### ISSUE THREAD

**Issue by OneAdder** [okonek/tidal-cli-client#46]
I can't really play anything. The app freezes at this point. I try pressing anything. Buttons with copy work. But I can't do anything further.
What could it be?
My terminal emulator is Konsole
![tidalcli](https://user-images.githubusercontent.com/19834976/45585848-50af5900-b8f4-11e8-8f2b-e040aa5cc1fd.png)

**Comment by okonek** [comment]
Can't you just press ":"?

**Comment by OneAdder** [comment]
Sorry, missed this point from the instruction. That was a stupid question :)
By the way, thanks for the app. Now I don't need to install Chrome on GNU/Linux
