### ISSUE TITLE
Can't start or install app app

### ISSUE THREAD

**Issue by lenarddome** [okonek/tidal-cli-client#6]
Followed instructions, npm install was flawless, but npm run app produced this output,
installing from npm rep also produces this or similar output. ( with "sudo npm -g i tidal-cli-client)

[npm-debug.log](https://github.com/okonek/tidal-cli-client/files/1634570/npm-debug.log)

**Comment by okonek** [comment]
I think the problem is that you have an old version of npm and Node. Maybe if you will update the problem will be solved.

**Comment by MartonEstok** [comment]
I could not install either with similar errors on Linux Mint latest. Node is 8+

**Comment by okonek** [comment]
I'll check it in a minute on my VM

**Comment by okonek** [comment]
@MartonEstok Could you also post your output please? It'll help me debug.

**Comment by okonek** [comment]
Ok, so I ran it on my VM and figured out that it's a problem with robotjs. I have changed robotjs to node-key-sender, tested and now it should work. After update to node 9.4.0 I have noticed problem with deasync, but it's not fault of my app, so I suggest not to update to 9.4.0 until it's repaired.

**Comment by MartonEstok** [comment]
thank you @okonek and sorry for not sending the logs - I dont have access to this PC at this point. I will test this as soon as I do.

**Comment by CodaTheOtaku** [comment]
@okonek I can confirm your solution worked for me, running the client in i3 on Arch. I uninstalled node 9.4.0 and instead used 9.3.0 to install it.

**Comment by okonek** [comment]
Can I close the issue? I think the problem is solved.

**Comment by lenarddome** [comment]
Yes you can, it works for me too! Sorry for the late response and thank you very much for the quick fix!
