### ISSUE TITLE
Error when selecting artist

### ISSUE THREAD

**Issue by twhiston** [okonek/tidal-cli-client#7]
Hi, running on Fedora 27, when i try to search for an artist and select them in the client I get the error
```
(node:17186) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'tw' of undefined───────────┐
(node:17186) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by okonek** [comment]
I'll try to solve it. Have you installed app from Github or npm? Also, do you have the latest version?

**Comment by twhiston** [comment]
Hi, I installed it with `npm -g i tidal-cli-client@latest` so it should be the latest.
node v8.9.4
npm v5.6.0

**Comment by okonek** [comment]
Sorry for inactivity, but I was on holiday. Now I'm solving it.

**Comment by okonek** [comment]
Oh, I made a stupid mistake. I forget that w3m browser (it seems strange that my app needs browser, but it's the only way I can display images) is required for my program. I'll add it to README, that it's needed. When you install it, there won't be any problem.
Thank you for reporting it!
