### ISSUE TITLE
audio quality

### ISSUE THREAD

**Issue by hy37id** [okonek/tidal-cli-client#9]
Do you think is possible to play Hi-Fi quality audio, not only High quality?
I've tried to change config file, but it didn't work.
Kind regards
Hy37id

**Comment by okonek** [comment]
I'm now working on it.
Thanks for your patience.

**Comment by hy37id** [comment]
Not a problem, good to know and good luck!
Best regards
hy37id

**Comment by okonek** [comment]
Just pushed it in version 1.2.5 Closing
